server:
  port: 7766
spring:
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 5

  redis:
    lettuce:
      pool:
        max-wait: 5000
        max-active: 114514
    host: 127.0.0.1
    port: 6379
logging:
  config: classpath:logback-spring.xml

jwt:
  header: Auth
  secretKey: Y2VyZXNodXpoaXRpbmduaXpoZW5iYW5nY2VyZXNodXpoaXRpbmduaXpoZW5iYW5n2VyZXNodXpoaXRpbmduaXpoZW5iYW5n2VyZXNodXpoaXRpbmduaXpoZW5iYW5n
  expire: 114514

http:
  maxTotal: 5
  defaultMaxPerRoute: 5
  connectTimeout: 1000
  connectionRequestTimeout: 3000
pagehelper:
  helper-dialect: mysql
  reasonable: true  #分页参数合理化 如 -1时 会查询 0
  params: countSql
  auto-runtime-dialect: true
Savegame:
  savetime: 604800000  #7*24*60*60*1000  7天(ms)

captcha:
  header: CAPTCHA_
  timeout: 30

accesslimit:
  limitheader: accesslimit